# Generated by Django 5.0.6 on 2024-07-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingInventoryTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=99)),
                ('desc', models.CharField(max_length=1000)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('p_date', models.DateField()),
                ('stock', models.IntegerField(default=10)),
                ('seller', models.CharField(default='', max_length=100)),
                ('keywords', models.CharField(default='', max_length=1000)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
