# Generated by Django 5.0.6 on 2024-07-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinginventorytransfer',
            name='refill',
            field=models.BooleanField(default=False),
        ),
    ]
