# Generated by Django 5.0.6 on 2024-07-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_pendinginventorytransfer_refill'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinginventorytransfer',
            name='p_id',
            field=models.IntegerField(default=0),
        ),
    ]
