# Generated by Django 5.0.7 on 2024-08-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_pendinginventorytransfer_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinginventorytransfer',
            name='p_plan',
            field=models.CharField(default='golden', max_length=50),
        ),
    ]
