# Generated by Django 5.0.7 on 2024-09-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_pendinginventorytransfer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinginventorytransfer',
            name='is_active',
        ),
    ]
