# Generated by Django 5.0.6 on 2024-07-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
