# Generated by Django 5.0.6 on 2024-07-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_pageview_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
