# Generated by Django 5.0.7 on 2024-09-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_withdrawrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='account_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='ifsc_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
