# Generated by Django 5.0.6 on 2024-07-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=350)),
                ('p_date', models.DateField()),
            ],
        ),
    ]
