# Generated by Django 5.0.6 on 2024-07-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_orderupdate_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cart_json', models.CharField(max_length=20000)),
            ],
        ),
    ]
