# Generated by Django 5.0.6 on 2024-07-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(default='', max_length=100),
        ),
    ]
