# Generated by Django 5.0.6 on 2024-07-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_stock_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
