# Generated by Django 5.0.6 on 2024-07-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='users',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
