# Generated by Django 5.0.6 on 2024-07-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_orders_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='users',
            new_name='sellers',
        ),
    ]
