# Generated by Django 5.0.6 on 2024-07-26 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlyWholesale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Wholesale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
