# Generated by Django 5.0.6 on 2024-07-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_wholesale_product_delete_onlywholesale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.IntegerField(default=5),
        ),
    ]
