# Generated by Django 5.0.6 on 2024-07-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='ratings',
            field=models.IntegerField(default=5),
        ),
    ]
