# Generated by Django 5.0.7 on 2024-08-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_orders_address_remove_orders_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.addressline'),
        ),
    ]
