# Generated by Django 5.0.7 on 2024-08-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_userlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productreview',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
