# Generated by Django 5.0.7 on 2024-08-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_productreview_dislikes_productreview_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikes',
            name='type',
        ),
    ]
