# Generated by Django 5.0.7 on 2024-08-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lifetime_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
