# Generated by Django 5.0.7 on 2024-08-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_product_lifetime_sales_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_plan',
            field=models.CharField(default='golden', max_length=50),
        ),
    ]
