# Generated by Django 5.0.7 on 2024-09-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
