# Generated by Django 5.0.7 on 2024-09-21 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_canceledorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productreview'),
        ),
    ]
